### ISSUE TITLE
Doesn't work with IE 8

### ISSUE THREAD

**Issue by Anar-zz** [antony/grails-ajax-uploader#1] opened 2011-04-20 19:48 UTC
Hi,
The code did not work for me in IE.
I needed to add the multipartHttpServletRequest portion to handle form submission from iFrame. 

```
    //For Iframe form upload
    if(request instanceof MultipartHttpServletRequest)
    {   
        try {   
            MultipartHttpServletRequest mpr = (MultipartHttpServletRequest)request;  
            def CommonsMultipartFile uploadedFile = mpr.getFile('qqfile');
            imageService.storeImage (uploaded, uploadedFile.inputStream);
            render("<html><body>{success:true, src:\"${imagesContext}${uid}\", imageId:\"${uid}\"}</body></html>")
        } catch (Exception e) {
            render("<html><body>{success:false}</body></html>")
        }
    }
    //For XHR stream send
    else {
        try {
            imageService.storeImage (uploaded, request.inputStream);
            render([success:true, src:"${imagesContext}${uid}", imageId:"${uid}"] as JSON)
        } catch (Exception e) {

            render([success:false] as JSON) 
        }
    }
```

Could I ask you to update the plugin so it'll work for IE too.
PS. You can see the functioning code on http://www.gardennut.com

**Comment by antony** [comment] 2011-04-20 20:02
Hi Anar,

Thanks for your submission. I see the problem is upstream, in Andrew Valum's source code. I'll see what I can do to get this fixed for you ASAP.

Cheers,
Antony

**Comment by antony** [comment] 2011-04-20 20:03
Wait, cancel that - I just realised that this is controller code! Sorry, it's been a long day.

I'll fix this as soon as I get an opportunity - probably this weekend.

**Comment by antony** [comment] 2011-04-21 19:21
This is now fixed + tested on IE8. I also fixed another issue whereby IE would try to download the JSON rather than render it to the XHR object.

**Closed as completed by antony** 2011-04-21 19:21 UTC
